import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainContainer from '../components/MainContainer'
import Section from '../components/Section'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <MainContainer>
        <Section sectionTitle='A' sectionDescription='ASAF'/>
        <Section sectionTitle='B' sectionDescription='ASASFGAAF'/>
        <Section sectionTitle='C' sectionDescription='ASAASGASGF'/>
        <Section sectionTitle='D' sectionDescription='ASASGASGSAGFASAF'/>
      </MainContainer>
      </>
  )
}
